// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

// Protobuf Java Version: 3.25.2
package com.blubank.doctorappointment.protos;

public final class DoctorProtos {
  private DoctorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_blubank_doctorappointment_Doctor_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_blubank_doctorappointment_Doctor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014doctor.proto\022\035com.blubank.doctorappoin" +
      "tment\032\037google/protobuf/timestamp.proto\"a" +
      "\n\006Doctor\022\021\n\tfull_name\030\001 \001(\t\022\024\n\014medical_c" +
      "ode\030\002 \001(\t\022.\n\ncreated_at\030\003 \001(\0132\032.google.p" +
      "rotobuf.TimestampB6\n$com.blubank.doctora" +
      "ppointment.protosB\014DoctorProtosP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_blubank_doctorappointment_Doctor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_blubank_doctorappointment_Doctor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_blubank_doctorappointment_Doctor_descriptor,
        new java.lang.String[] { "FullName", "MedicalCode", "CreatedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
