// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

// Protobuf Java Version: 3.25.2
package com.blubank.doctorappointment.protos;

public interface DoctorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.blubank.doctorappointment.Doctor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string full_name = 1;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 1;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string medical_code = 2;</code>
   * @return The medicalCode.
   */
  java.lang.String getMedicalCode();
  /**
   * <code>string medical_code = 2;</code>
   * @return The bytes for medicalCode.
   */
  com.google.protobuf.ByteString
      getMedicalCodeBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 3;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 3;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
